[rust]
debuginfo-level = 1

[package]
name = "chess"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
bitintr = { version = "0.3.0" }

[features]
default = []
pext = []
